-- 0005_seed_opportunities.sql
-- Description: Seeds initial organizers and verified opportunities.
-- Reason: Populates the platform with initial discovery data from mockOpportunities.js.

-- Insert Organizers
INSERT INTO public.organizers (id, name, type, website, logo)
VALUES
  ('techfest', 'Techfest, IIT Bombay', 'College', 'https://techfest.org', 'https://www.google.com/s2/favicons?domain=techfest.org&sz=128'),
  ('iitm', 'IIT Madras', 'College', 'https://www.iitm.ac.in', 'https://www.google.com/s2/favicons?domain=www.iitm.ac.in&sz=128'),
  ('iitd', 'IIT Delhi', 'College', 'https://www.iitd.ac.in', 'https://www.google.com/s2/favicons?domain=www.iitd.ac.in&sz=128'),
  ('iitkgp', 'IIT Kharagpur', 'College', 'https://iitkgp.ac.in', 'https://www.google.com/s2/favicons?domain=iitkgp.ac.in&sz=128'),
  ('iith', 'IIT Hyderabad', 'College', 'https://iith.ac.in', 'https://www.google.com/s2/favicons?domain=iith.ac.in&sz=128'),
  ('iitg', 'IIT Guwahati', 'College', 'https://iitg.ac.in', 'https://www.google.com/s2/favicons?domain=iitg.ac.in&sz=128'),
  ('bits', 'BITS Pilani', 'College', 'https://bits-pilani.ac.in', 'https://www.google.com/s2/favicons?domain=bits-pilani.ac.in&sz=128'),
  ('nitt', 'NIT Trichy', 'College', 'https://www.nitt.edu', 'https://www.google.com/s2/favicons?domain=www.nitt.edu&sz=128'),
  ('nitk', 'NIT Karnataka', 'College', 'https://nitk.ac.in', 'https://www.google.com/s2/favicons?domain=nitk.ac.in&sz=128'),
  ('iiith', 'IIIT Hyderabad', 'College', 'https://iiit.ac.in', 'https://www.google.com/s2/favicons?domain=iiit.ac.in&sz=128'),
  ('vit', 'VIT Vellore', 'College', 'https://vit.ac.in', 'https://www.google.com/s2/favicons?domain=vit.ac.in&sz=128'),
  ('iisc', 'IISc Bangalore', 'College', 'https://iisc.ac.in', 'https://www.google.com/s2/favicons?domain=iisc.ac.in&sz=128'),
  ('coep', 'COEP Tech Pune', 'College', 'https://coeptech.ac.in', 'https://www.google.com/s2/favicons?domain=coeptech.ac.in&sz=128'),
  ('google', 'Google', 'Company', 'https://google.com', 'https://www.google.com/s2/favicons?domain=google.com&sz=128'),
  ('tcs', 'TCS', 'Company', 'https://www.tcs.com', 'https://www.google.com/s2/favicons?domain=www.tcs.com&sz=128'),
  ('wipro', 'Wipro', 'Company', 'https://wipro.com', 'https://www.google.com/s2/favicons?domain=wipro.com&sz=128'),
  ('infosys', 'Infosys', 'Company', 'https://infosys.com', 'https://www.google.com/s2/favicons?domain=infosys.com&sz=128'),
  ('flipkart', 'Flipkart', 'Company', 'https://flipkart.com', 'https://www.google.com/s2/favicons?domain=flipkart.com&sz=128'),
  ('razorpay', 'Razorpay', 'Startup', 'https://razorpay.com', 'https://www.google.com/s2/favicons?domain=razorpay.com&sz=128'),
  ('cred', 'CRED', 'Startup', 'https://cred.club', 'https://www.google.com/s2/favicons?domain=cred.club&sz=128'),
  ('swiggy', 'Swiggy', 'Startup', 'https://swiggy.com', 'https://www.google.com/s2/favicons?domain=swiggy.com&sz=128'),
  ('groww', 'Groww', 'Startup', 'https://groww.in', 'https://www.google.com/s2/favicons?domain=groww.in&sz=128'),
  ('postman', 'Postman', 'Startup', 'https://postman.com', 'https://www.google.com/s2/favicons?domain=postman.com&sz=128'),
  ('freshworks', 'Freshworks', 'Startup', 'https://freshworks.com', 'https://www.google.com/s2/favicons?domain=freshworks.com&sz=128'),
  ('unstop', 'Unstop', 'Platform', 'https://unstop.com', 'https://www.google.com/s2/favicons?domain=unstop.com&sz=128'),
  ('nptel', 'NPTEL', 'Platform', 'https://onlinecourses.nptel.ac.in', 'https://www.google.com/s2/favicons?domain=onlinecourses.nptel.ac.in&sz=128'),
  ('coursera', 'Coursera', 'Platform', 'https://coursera.org', 'https://www.google.com/s2/favicons?domain=coursera.org&sz=128')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  type = EXCLUDED.type,
  website = EXCLUDED.website,
  logo = EXCLUDED.logo;

-- Insert Opportunities
INSERT INTO public.opportunities (
  id, title, description, category, theme, organizer_id, format, location,
  fee, start_date, end_date, deadline, level, interests, skills, team_size,
  hours_per_week, min_year, registration_url, source_url, last_verified, verified, warning
)
VALUES
  (
    'opp-1',
    'Sustainable Tech Hackathon',
    'Build a working prototype that reduces campus energy or waste in 36 hours.',
    'hackathons',
    'Sustainability',
    'techfest',
    'Hybrid',
    'Mumbai',
    0,
    '2026-12-12',
    '2026-12-14',
    '2026-11-25',
    'Intermediate',
    '{"Sustainability","Web Development","Social Impact"}'::text[],
    '{"React","Python"}'::text[],
    '{"min":2,"max":4}'::jsonb,
    12,
    NULL,
    'https://techfest.org',
    'https://techfest.org',
    '2026-10-08T10:15:00+05:30',
    true,
    NULL
  ),
  (
    'opp-2',
    'Climate Data Challenge',
    'Use open climate datasets to forecast and visualise regional heat risk.',
    'hackathons',
    'Climate & Data',
    'iitm',
    'Online',
    'Online',
    0,
    '2027-01-16',
    '2027-01-18',
    '2027-01-05',
    'Intermediate',
    '{"Sustainability","Data Science","AI & Machine Learning"}'::text[],
    '{"Python","SQL"}'::text[],
    '{"min":1,"max":3}'::jsonb,
    9,
    NULL,
    'https://www.iitm.ac.in',
    'https://www.iitm.ac.in',
    '2026-10-05T16:40:00+05:30',
    true,
    NULL
  ),
  (
    'opp-3',
    'FinTech Build Sprint',
    'Design a payments or lending feature using real-world sandbox APIs.',
    'hackathons',
    'FinTech',
    'razorpay',
    'In-person',
    'Bengaluru',
    0,
    '2026-12-05',
    '2026-12-06',
    '2026-11-20',
    'Intermediate',
    '{"Finance","Web Development","Entrepreneurship"}'::text[],
    '{"JavaScript","Node"}'::text[],
    '{"min":2,"max":4}'::jsonb,
    10,
    2,
    'https://razorpay.com',
    'https://razorpay.com',
    '2026-10-07T11:00:00+05:30',
    true,
    NULL
  ),
  (
    'opp-4',
    'Campus Mobile App Hackathon',
    'Ship a mobile app that solves a real problem on your campus.',
    'hackathons',
    'Mobile & Social Impact',
    'bits',
    'Hybrid',
    'Pilani',
    150,
    '2026-12-19',
    '2026-12-20',
    '2026-12-08',
    'Beginner',
    '{"Mobile Apps","Social Impact"}'::text[],
    '{"Flutter","React Native"}'::text[],
    '{"min":2,"max":4}'::jsonb,
    10,
    NULL,
    'https://bits-pilani.ac.in',
    'https://bits-pilani.ac.in',
    '2026-09-21T09:00:00+05:30',
    false,
    'Fee differs between the organizer site and a listing site.'
  ),
  (
    'opp-5',
    'Open Source & Dev Tools Hackathon',
    'Create or extend an open-source developer tool with API-first design.',
    'hackathons',
    'Developer Tools',
    'postman',
    'Online',
    'Online',
    0,
    '2026-11-28',
    '2026-11-30',
    '2026-11-18',
    'Intermediate',
    '{"Cloud & DevOps","Web Development"}'::text[],
    '{"JavaScript","APIs"}'::text[],
    '{"min":1,"max":4}'::jsonb,
    8,
    NULL,
    'https://postman.com',
    'https://postman.com',
    '2026-10-06T14:20:00+05:30',
    true,
    NULL
  ),
  (
    'opp-6',
    'AI for Bharat Hackathon',
    'Apply machine learning to a public-service problem in healthcare or education.',
    'hackathons',
    'AI for Good',
    'iiith',
    'In-person',
    'Hyderabad',
    300,
    '2027-01-23',
    '2027-01-25',
    '2027-01-10',
    'Advanced',
    '{"AI & Machine Learning","Social Impact"}'::text[],
    '{"Python","PyTorch"}'::text[],
    '{"min":2,"max":4}'::jsonb,
    14,
    3,
    'https://iiit.ac.in',
    'https://iiit.ac.in',
    '2026-10-04T12:30:00+05:30',
    true,
    NULL
  ),
  (
    'opp-7',
    'Beginner Web Development Workshop',
    'Build and publish your first website in one afternoon, no experience needed.',
    'workshops',
    'Web Basics',
    'google',
    'Online',
    'Online',
    0,
    '2026-11-21',
    '2026-11-21',
    '2026-11-19',
    'Beginner',
    '{"Web Development"}'::text[],
    '{"HTML","CSS"}'::text[],
    NULL,
    3,
    NULL,
    'https://google.com',
    'https://google.com',
    '2026-10-08T18:05:00+05:30',
    true,
    NULL
  ),
  (
    'opp-8',
    'UI/UX Design Sprint Workshop',
    'Go from user research to a clickable prototype in a hands-on design sprint.',
    'workshops',
    'Product Design',
    'freshworks',
    'In-person',
    'Chennai',
    0,
    '2026-12-02',
    '2026-12-03',
    '2026-11-24',
    'Beginner',
    '{"Design","Mobile Apps"}'::text[],
    '{"Figma"}'::text[],
    NULL,
    4,
    NULL,
    'https://freshworks.com',
    'https://freshworks.com',
    '2026-10-03T10:00:00+05:30',
    true,
    NULL
  ),
  (
    'opp-9',
    'Robotics & Automation Workshop',
    'Assemble and program a line-following robot with Arduino.',
    'workshops',
    'Robotics',
    'iitkgp',
    'In-person',
    'Kharagpur',
    1200,
    '2026-12-14',
    '2026-12-16',
    '2026-12-01',
    'Beginner',
    '{"Robotics"}'::text[],
    '{"Arduino"}'::text[],
    NULL,
    5,
    NULL,
    'https://iitkgp.ac.in',
    'https://iitkgp.ac.in',
    '2026-10-02T15:10:00+05:30',
    true,
    NULL
  ),
  (
    'opp-10',
    'Cybersecurity Essentials Workshop',
    'Learn how attacks work and how to defend against them with live labs.',
    'workshops',
    'Security',
    'vit',
    'Hybrid',
    'Vellore',
    250,
    '2026-12-09',
    '2026-12-10',
    '2026-11-30',
    'Beginner',
    '{"Cybersecurity"}'::text[],
    '{"Linux","Networking"}'::text[],
    NULL,
    5,
    NULL,
    'https://vit.ac.in',
    'https://vit.ac.in',
    '2026-10-01T09:45:00+05:30',
    true,
    NULL
  ),
  (
    'opp-11',
    'Cloud & DevOps Bootcamp Workshop',
    'Deploy a containerised app to the cloud and automate it with CI/CD.',
    'workshops',
    'Cloud',
    'wipro',
    'Online',
    'Online',
    0,
    '2026-12-12',
    '2026-12-13',
    '2026-12-04',
    'Intermediate',
    '{"Cloud & DevOps"}'::text[],
    '{"Linux","Docker"}'::text[],
    NULL,
    6,
    NULL,
    'https://wipro.com',
    'https://wipro.com',
    '2026-10-06T13:00:00+05:30',
    true,
    NULL
  ),
  (
    'opp-12',
    'Investing Case Challenge',
    'Analyse a company and pitch an investment thesis to a panel of professionals.',
    'competitions',
    'Finance',
    'groww',
    'Online',
    'Online',
    0,
    '2026-12-07',
    '2026-12-20',
    '2026-11-30',
    'Intermediate',
    '{"Finance","Entrepreneurship"}'::text[],
    '{"Excel","Pitching"}'::text[],
    '{"min":1,"max":3}'::jsonb,
    6,
    NULL,
    'https://groww.in',
    'https://groww.in',
    '2026-10-07T17:25:00+05:30',
    true,
    NULL
  ),
  (
    'opp-13',
    'Social Impact Innovation Challenge',
    'Pitch a scalable idea that improves access to clean water, food or learning.',
    'competitions',
    'Social Impact',
    'coep',
    'In-person',
    'Pune',
    300,
    '2027-01-09',
    '2027-01-10',
    '2026-12-12',
    'Intermediate',
    '{"Social Impact","Sustainability","Entrepreneurship"}'::text[],
    '{"Design","Pitching"}'::text[],
    '{"min":2,"max":5}'::jsonb,
    6,
    NULL,
    'https://coeptech.ac.in',
    'https://coeptech.ac.in',
    '2026-09-18T08:30:00+05:30',
    false,
    'Deadline is missing on one source.'
  ),
  (
    'opp-14',
    'Campus Cybersecurity CTF',
    'Solve web, crypto and forensics challenges in a 24-hour capture the flag.',
    'competitions',
    'Security',
    'iith',
    'Online',
    'Online',
    200,
    '2026-12-05',
    '2026-12-06',
    '2026-11-28',
    'Intermediate',
    '{"Cybersecurity"}'::text[],
    '{"Linux","Networking"}'::text[],
    '{"min":1,"max":4}'::jsonb,
    8,
    NULL,
    'https://iith.ac.in',
    'https://iith.ac.in',
    '2026-10-05T11:50:00+05:30',
    true,
    NULL
  ),
  (
    'opp-15',
    'Product Management Case Competition',
    'Solve a live product problem and present your roadmap to PMs.',
    'competitions',
    'Product',
    'flipkart',
    'Hybrid',
    'Bengaluru',
    0,
    '2027-01-17',
    '2027-01-17',
    '2026-12-28',
    'Intermediate',
    '{"Entrepreneurship","Design"}'::text[],
    '{"Pitching","Analytics"}'::text[],
    '{"min":2,"max":3}'::jsonb,
    7,
    3,
    'https://flipkart.com',
    'https://flipkart.com',
    '2026-10-08T09:10:00+05:30',
    true,
    NULL
  ),
  (
    'opp-16',
    'Data Science Olympiad',
    'Compete on a timed series of modelling and analytics problems.',
    'competitions',
    'Data Science',
    'iitg',
    'Online',
    'Online',
    0,
    '2027-01-30',
    '2027-01-31',
    '2027-01-15',
    'Advanced',
    '{"Data Science","AI & Machine Learning"}'::text[],
    '{"Python","Statistics"}'::text[],
    NULL,
    10,
    NULL,
    'https://iitg.ac.in',
    'https://iitg.ac.in',
    '2026-10-04T19:00:00+05:30',
    true,
    NULL
  ),
  (
    'opp-17',
    'Frontend Engineering Intern',
    'Build user-facing features in React alongside the core product team.',
    'internships',
    'Software Engineering',
    'cred',
    'Hybrid',
    'Bengaluru',
    0,
    '2027-01-11',
    '2027-06-30',
    '2026-12-01',
    'Intermediate',
    '{"Web Development","Design"}'::text[],
    '{"React","JavaScript"}'::text[],
    NULL,
    20,
    3,
    'https://cred.club',
    'https://cred.club',
    '2026-10-08T12:00:00+05:30',
    true,
    NULL
  ),
  (
    'opp-18',
    'Data Science Research Intern',
    'Work with a research group on applied machine learning for real datasets.',
    'internships',
    'Research',
    'iisc',
    'Online',
    'Online',
    0,
    '2027-01-04',
    '2027-04-30',
    '2026-12-15',
    'Advanced',
    '{"Data Science","AI & Machine Learning"}'::text[],
    '{"Python","Statistics"}'::text[],
    NULL,
    15,
    4,
    'https://iisc.ac.in',
    'https://iisc.ac.in',
    '2026-10-03T16:00:00+05:30',
    true,
    NULL
  ),
  (
    'opp-19',
    'Software Engineering Intern',
    'A summer internship working on production software with a mentor.',
    'internships',
    'Software Engineering',
    'google',
    'Hybrid',
    'Hyderabad',
    0,
    '2027-05-17',
    '2027-08-06',
    '2026-11-27',
    'Intermediate',
    '{"Web Development","Cloud & DevOps"}'::text[],
    '{"Python","Algorithms"}'::text[],
    NULL,
    40,
    2,
    'https://google.com',
    'https://google.com',
    '2026-10-09T08:00:00+05:30',
    true,
    NULL
  ),
  (
    'opp-20',
    'Product Design Intern',
    'Design flows for a high-traffic consumer app, from research to hand-off.',
    'internships',
    'Design',
    'swiggy',
    'In-person',
    'Bengaluru',
    0,
    '2027-01-18',
    '2027-07-16',
    '2026-12-10',
    'Intermediate',
    '{"Design","Mobile Apps"}'::text[],
    '{"Figma","Prototyping"}'::text[],
    NULL,
    30,
    2,
    'https://swiggy.com',
    'https://swiggy.com',
    '2026-10-02T10:30:00+05:30',
    true,
    NULL
  ),
  (
    'opp-21',
    'Cloud Engineering Intern',
    'Support cloud migration projects and learn infrastructure as code.',
    'internships',
    'Cloud',
    'tcs',
    'In-person',
    'Mumbai',
    0,
    '2027-01-25',
    '2027-06-25',
    '2026-12-18',
    'Intermediate',
    '{"Cloud & DevOps","Data Science"}'::text[],
    '{"Linux","Python"}'::text[],
    NULL,
    35,
    3,
    'https://www.tcs.com',
    'https://www.tcs.com',
    '2026-09-25T13:15:00+05:30',
    false,
    'Stipend and duration differ between sources.'
  ),
  (
    'opp-22',
    'Machine Learning Foundations',
    'A self-paced introduction to supervised learning, from theory to code.',
    'courses',
    'Machine Learning',
    'nptel',
    'Online',
    'Online',
    0,
    NULL,
    NULL,
    '2026-12-05',
    'Beginner',
    '{"AI & Machine Learning","Data Science"}'::text[],
    '{"Python"}'::text[],
    NULL,
    5,
    NULL,
    'https://onlinecourses.nptel.ac.in',
    'https://onlinecourses.nptel.ac.in',
    '2026-10-06T09:30:00+05:30',
    true,
    NULL
  ),
  (
    'opp-23',
    'Cloud Computing Basics',
    'Understand cloud services, networking and security from first principles.',
    'courses',
    'Cloud',
    'coursera',
    'Online',
    'Online',
    800,
    NULL,
    NULL,
    '2026-12-20',
    'Beginner',
    '{"Cloud & DevOps"}'::text[],
    '{"Linux"}'::text[],
    NULL,
    4,
    NULL,
    'https://coursera.org',
    'https://coursera.org',
    '2026-10-01T15:45:00+05:30',
    true,
    NULL
  ),
  (
    'opp-24',
    'Entrepreneurship Essentials',
    'Validate an idea, build a business model and plan your first launch.',
    'courses',
    'Entrepreneurship',
    'iitd',
    'Online',
    'Online',
    0,
    '2026-11-30',
    '2027-01-31',
    '2026-11-22',
    'Beginner',
    '{"Entrepreneurship","Finance"}'::text[],
    '{"Pitching"}'::text[],
    NULL,
    4,
    NULL,
    'https://www.iitd.ac.in',
    'https://www.iitd.ac.in',
    '2026-10-05T10:20:00+05:30',
    true,
    NULL
  ),
  (
    'opp-25',
    'Introduction to Cybersecurity',
    'Cover threats, cryptography and secure coding with short weekly labs.',
    'courses',
    'Security',
    'nitk',
    'Online',
    'Online',
    0,
    NULL,
    NULL,
    '2026-12-12',
    'Beginner',
    '{"Cybersecurity"}'::text[],
    '{"Networking"}'::text[],
    NULL,
    3,
    NULL,
    'https://nitk.ac.in',
    'https://nitk.ac.in',
    '2026-10-07T14:00:00+05:30',
    true,
    NULL
  ),
  (
    'opp-26',
    'Mobile App Development with Flutter',
    'Learn Flutter by building three complete apps, with mentor feedback.',
    'courses',
    'Mobile',
    'nitt',
    'Hybrid',
    'Tiruchirappalli',
    500,
    '2026-12-01',
    '2027-01-15',
    '2026-11-23',
    'Beginner',
    '{"Mobile Apps","Design"}'::text[],
    '{"Flutter"}'::text[],
    NULL,
    6,
    NULL,
    'https://www.nitt.edu',
    'https://www.nitt.edu',
    '2026-10-03T12:40:00+05:30',
    true,
    NULL
  ),
  (
    'opp-27',
    'Web Development Crash Course',
    'HTML, CSS and JavaScript in four weeks, with a portfolio project.',
    'courses',
    'Web',
    'unstop',
    'Online',
    'Online',
    0,
    '2026-11-16',
    '2026-12-14',
    '2026-11-12',
    'Beginner',
    '{"Web Development"}'::text[],
    '{"HTML","CSS","JavaScript"}'::text[],
    NULL,
    6,
    NULL,
    'https://unstop.com',
    'https://unstop.com',
    '2026-10-08T15:30:00+05:30',
    true,
    NULL
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  theme = EXCLUDED.theme,
  organizer_id = EXCLUDED.organizer_id,
  format = EXCLUDED.format,
  location = EXCLUDED.location,
  fee = EXCLUDED.fee,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  deadline = EXCLUDED.deadline,
  level = EXCLUDED.level,
  interests = EXCLUDED.interests,
  skills = EXCLUDED.skills,
  team_size = EXCLUDED.team_size,
  hours_per_week = EXCLUDED.hours_per_week,
  min_year = EXCLUDED.min_year,
  registration_url = EXCLUDED.registration_url,
  source_url = EXCLUDED.source_url,
  last_verified = EXCLUDED.last_verified,
  verified = EXCLUDED.verified,
  warning = EXCLUDED.warning;
