-- 0012_seed_demo_students.sql
-- Description: Seeds the 16 invented students (u-1 ... u-16) from src/data/mockPeople.js, and the connections between them.
-- Reason: The Connections feed, People pages and Squad Hub need other students to show. These are DEMO students:
-- the names and colleges are invented, they have no Google login (profiles.is_demo = true), and their emails are
-- the example.com addresses from src/data/mockSquads.js (they are only ever revealed after double opt-in).
--
-- To remove all demo data later:  delete from public.profiles where is_demo;   (everything linked to them goes too)

insert into public.profiles
  (id, email, name, onboarded, skills, interests, is_beginner, year, location, budget,
   headline, about, college, is_demo, demo_connection_count)
values
  (public.demo_uid(1),  'priya.nair@example.com', 'Priya Nair', true,
    array['Flutter','React Native'], array['Mobile Apps','Social Impact'], false, 2, 'Pilani', 500,
    'Mobile and web developer in the making',
    'Second-year student who likes shipping small apps. Looking for hackathon teammates.',
    'BITS Pilani', true, 214),
  (public.demo_uid(2),  'aarav.mehta@example.com', 'Aarav Mehta', true,
    array['Python','SQL','Statistics'], array['Data Science','AI & Machine Learning','Sustainability'], false, 3, 'Chennai', 500,
    'Data science and machine learning enthusiast',
    'Third-year student working on climate data projects. Happy to help beginners get started.',
    'IIT Madras', true, 342),
  (public.demo_uid(3),  'rohan.iyer@example.com', 'Rohan Iyer', true,
    array['Python','PyTorch'], array['AI & Machine Learning','Data Science'], false, 4, 'Tiruchirappalli', 500,
    'Final-year student exploring machine learning',
    'Finishing my last year and preparing for research internships. I share notes on the courses I complete.',
    'NIT Trichy', true, 289),
  (public.demo_uid(4),  'ananya.sharma@example.com', 'Ananya Sharma', true,
    array['Python','PyTorch','Linux'], array['AI & Machine Learning','Cybersecurity'], false, 3, 'Hyderabad', 500,
    'AI and security hobbyist',
    'Into deep learning and capture-the-flag contests. Currently looking for a team for an AI hackathon.',
    'IIIT Hyderabad', true, 301),
  (public.demo_uid(5),  'kabir.singh@example.com', 'Kabir Singh', true,
    array['HTML','CSS'], array['Web Development'], true, 1, 'Vellore', 500,
    'First-year learning web development',
    'Just started coding. Trying out one workshop every month.',
    'VIT Vellore', true, 96),
  (public.demo_uid(6),  'meera.joshi@example.com', 'Meera Joshi', true,
    array['Figma','React'], array['Design','Web Development'], false, 2, 'Pune', 500,
    'Design-minded engineering student',
    'Second-year student who enjoys design and frontend work. Preparing for my first hackathon.',
    'COEP Tech Pune', true, 158),
  (public.demo_uid(7),  'arjun.reddy@example.com', 'Arjun Reddy', true,
    array['Python','Algorithms'], array['Data Science','AI & Machine Learning'], false, 4, 'Guwahati', 500,
    'Contest programmer and data science fan',
    'Final year. I practise for contests and help juniors with problem solving.',
    'IIT Guwahati', true, 410),
  (public.demo_uid(8),  'ishita.das@example.com', 'Ishita Das', true,
    array['Arduino','Python'], array['Robotics','Sustainability'], false, 2, 'Kharagpur', 500,
    'Robotics and sustainability tinkerer',
    'Building small robots, and putting together a team for a climate hackathon.',
    'IIT Kharagpur', true, 187),
  (public.demo_uid(9),  'dev.patel@example.com', 'Dev Patel', true,
    array['JavaScript','SQL'], array['Finance','Web Development'], false, 3, 'Surathkal', 500,
    'Finance and web development',
    'Third-year student building a personal finance tracker in my spare time.',
    'NIT Karnataka', true, 175),
  (public.demo_uid(10), 'sana.khan@example.com', 'Sana Khan', true,
    array['Linux','Networking'], array['Cybersecurity'], false, 4, 'Vellore', 500,
    'Cybersecurity student',
    'Final year, preparing for security roles. I play CTFs on weekends.',
    'VIT Vellore', true, 233),
  (public.demo_uid(11), 'riya.kapoor@example.com', 'Riya Kapoor', true,
    array['Figma','React'], array['Design','Web Development'], false, 2, 'Delhi', 500,
    'Product designer and frontend learner',
    'Designing apps and learning React. Open to design sprints and small teams.',
    'IIT Delhi', true, 126),
  (public.demo_uid(12), 'karan.malhotra@example.com', 'Karan Malhotra', true,
    array['Python','Statistics'], array['AI & Machine Learning','Data Science'], false, 3, 'Pilani', 500,
    'Machine learning with a statistics focus',
    'Studying machine learning from the statistics side. Enjoy reading papers with friends.',
    'BITS Pilani', true, 204),
  (public.demo_uid(13), 'zoya.ahmed@example.com', 'Zoya Ahmed', true,
    array['Linux','Networking'], array['Cybersecurity','Cloud & DevOps'], true, 1, 'Hyderabad', 500,
    'First-year security and cloud learner',
    'Starting out with Linux and networking labs.',
    'IIIT Hyderabad', true, 72),
  (public.demo_uid(14), 'nikhil.rao@example.com', 'Nikhil Rao', true,
    array['Pitching','Excel'], array['Entrepreneurship','Finance'], false, 4, 'Vellore', 500,
    'Aspiring founder',
    'Final year, running a small startup club on campus.',
    'VIT Vellore', true, 267),
  (public.demo_uid(15), 'tara.menon@example.com', 'Tara Menon', true,
    array['Python','Design'], array['Sustainability','Social Impact'], false, 2, 'Surathkal', 500,
    'Sustainability and data',
    'Working on waste-reduction projects on campus.',
    'NIT Karnataka', true, 141),
  (public.demo_uid(16), 'vikram.choudhary@example.com', 'Vikram Choudhary', true,
    array['Docker','Linux','JavaScript'], array['Cloud & DevOps','Web Development'], false, 3, 'Pune', 500,
    'Cloud and web developer',
    'Third-year student deploying side projects to the cloud.',
    'COEP Tech Pune', true, 192)
on conflict (id) do update set
  email = excluded.email,
  name = excluded.name,
  onboarded = excluded.onboarded,
  skills = excluded.skills,
  interests = excluded.interests,
  is_beginner = excluded.is_beginner,
  year = excluded.year,
  location = excluded.location,
  headline = excluded.headline,
  about = excluded.about,
  college = excluded.college,
  is_demo = excluded.is_demo,
  demo_connection_count = excluded.demo_connection_count;

-- Connections between the demo students (the connectionIds lists in mockPeople.js).
-- These are what make "mutual connections" work. Each pair is stored once.
insert into public.connections (requester_id, addressee_id, status, created_at, accepted_at)
select distinct
  public.demo_uid(least(l.person, o)),
  public.demo_uid(greatest(l.person, o)),
  'accepted',
  '2026-07-01T10:00:00+05:30'::timestamptz,
  '2026-07-01T10:00:00+05:30'::timestamptz
from (
  values
    (1,  array[2, 5, 6, 11]),
    (2,  array[1, 3, 4, 7, 12, 15]),
    (3,  array[2, 4, 7, 14]),
    (4,  array[2, 3, 10, 12, 13]),
    (5,  array[1, 6, 10]),
    (6,  array[1, 5, 8, 11, 16]),
    (7,  array[2, 3, 12]),
    (8,  array[6, 13, 15]),
    (9,  array[11, 14, 16]),
    (10, array[4, 5, 13]),
    (11, array[1, 6, 9]),
    (12, array[2, 4, 7]),
    (13, array[4, 8, 10]),
    (14, array[3, 9, 16]),
    (15, array[2, 8, 16]),
    (16, array[6, 9, 14, 15])
) as l(person, others),
unnest(l.others) as o
on conflict do nothing;
